// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjJBjUO-Lxtc4LDdl-rBQEwu8ZLzxW4c',
    appId: '1:558565645671:web:19ce6eb7960c44f07863c2',
    messagingSenderId: '558565645671',
    projectId: 'laporin-8b6af',
    authDomain: 'laporin-8b6af.firebaseapp.com',
    storageBucket: 'laporin-8b6af.firebasestorage.app',
    measurementId: 'G-R7Y6DZRL11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1RflY_Kh2oKZ51EBbhB15gIfhgnSrIFk',
    appId: '1:558565645671:android:a8f706cc5fbec4d77863c2',
    messagingSenderId: '558565645671',
    projectId: 'laporin-8b6af',
    storageBucket: 'laporin-8b6af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMNzFMeEznpoQP2ZlMYINbiMB6Ra64fsI',
    appId: '1:558565645671:ios:5f3ba16e7ed63aba7863c2',
    messagingSenderId: '558565645671',
    projectId: 'laporin-8b6af',
    storageBucket: 'laporin-8b6af.firebasestorage.app',
    androidClientId: '558565645671-cpjo03kohufn76sfikff35nm8n0gfhra.apps.googleusercontent.com',
    iosClientId: '558565645671-lr9fpbb79gntk9p00j1o756btv7b1tp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.laporin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMNzFMeEznpoQP2ZlMYINbiMB6Ra64fsI',
    appId: '1:558565645671:ios:5f3ba16e7ed63aba7863c2',
    messagingSenderId: '558565645671',
    projectId: 'laporin-8b6af',
    storageBucket: 'laporin-8b6af.firebasestorage.app',
    androidClientId: '558565645671-cpjo03kohufn76sfikff35nm8n0gfhra.apps.googleusercontent.com',
    iosClientId: '558565645671-lr9fpbb79gntk9p00j1o756btv7b1tp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.laporin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCjJBjUO-Lxtc4LDdl-rBQEwu8ZLzxW4c',
    appId: '1:558565645671:web:531ef4b6473185b77863c2',
    messagingSenderId: '558565645671',
    projectId: 'laporin-8b6af',
    authDomain: 'laporin-8b6af.firebaseapp.com',
    storageBucket: 'laporin-8b6af.firebasestorage.app',
    measurementId: 'G-BYMV1P3BZN',
  );

}